name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'  # Latest LTS Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build Angular project
        run: npm run build --base-href=/easyqz/


